

version: '3.8'

services:
    web:
        build: .
        command: gunicorn config.wsgi -b 0.0.0.0:8000
        volumes:
            - .:/django-professionals
        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - "DJANGO_SECRET_KEY=django-insecure-+yw)k03_p!c!c7q^-_44_@pr9tyt8i#fz9t6p$$r&%dr+p03)32"
            - "DJANGO_DEBUG=True"
            - "DJANGO_SECURE_SSL_REDIRECT=False"
            - "DJANGO_SECURE_HSTS_SECONDS=0"
            - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
            - "DJANGO_SECURE_HSTS_PRELOAD=False"
            - "DJANGO_SESSION_COOKIE_SECURE=False"
            - "DJANGO_CSRF_COOKIE_SECURE=False"
    
    db:
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
    postgres_data:
