

version: '3.9'

services: 
    web:
        build: .
        command: python /django-professionals/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/django-professionals
        ports:
            - 8000:8000

